### PR TITLE
refactor(saas): Improve Payment Page

### PR DESCRIPTION
**Pull request by DaniEnsi**
I thought that the payment page could have used some rework in terms of looks so i started with this... The ui is done, now only the functions new to be connected again...

image

### CODE REVIEW

**Comment by alifarooq9** [comment]
This UI is much better than the previous UI, I just have one suggestion. Make this uniform with other cards, others pages cards heading is not that big compare to this. Make this components similar to other pages components

**Comment by DaniEnsi** [comment]
I also optimised and fixed spelling in the confirm subscription modal. It now respects whether a subscription is made for the first time or if it is switched to from a previous one... 

image

**Comment by alifarooq9** [comment]
It is giving me this error while clicking on the subscribe button

Screenshot 2024-05-09 at 9 00 49 AM

**Comment by alifarooq9** [comment]
Okay got it why it's doing that, because you have changed the variant id. Can you please make the variant ids as an env.

**Comment by DaniEnsi** [comment]
@alifarooq9 Yeh, I think its because to use `useForm` I changed the page to `use client` instead of server rendering which now exposes the variant ids...

**Comment by alifarooq9** [comment]
> @alifarooq9 Yeh, I think its because to use `useForm` I changed the page to `use client` instead of server rendering which now exposes the variant ids...

Change hard quoted variant id to next public env variables like this `NEXT_PUBLIC_VARIANT_ID`, it will fix the issue.

**Comment by DaniEnsi** [comment]
@alifarooq9 I am not sure what you mean, the variant id is pulled from the pricing config file. Do you want me to remove it from there and add it to the .env?

**Comment by alifarooq9** [comment]
> @alifarooq9 I am not sure what you mean, the variant id is pulled from the pricing config file. Do you want me to remove it from there and add it to the .env?

Yes, replace the hard quoted variant numbers to env variables

**Comment by DaniEnsi** [comment]
> Yes, replace the hard quoted variant numbers to env variables

I cant reproduce the error somehow, even when deploying it... Also I checked the docs from lemonsqueezy and variant_ids are not sensitive so don't need to be stored in a .env...

**Comment by DaniEnsi** [comment]
Also if I add them to the env, that would just complicate it even further...

Thats from the docs:

No, `variant_id` does not need to be stored in an `.env` file. Typically, environment variables (stored in `.env` files) are used for sensitive or environment-specific settings, such as API keys, secrets, database URLs, and other configuration options that should not be hard-coded into your application's codebase due to security or flexibility reasons.

Variant IDs in Lemon Squeezy are specific to the products and their variations within your store. They are used programmatically to reference specific variants in API calls or within your application logic. These IDs are not sensitive secrets, but rather identifiers for application logic and thus would be used directly in your code where relevant, or stored in a database alongside product information, rather than in an `.env` file.

**Comment by DaniEnsi** [comment]
@alifarooq9 I tried for another like 30 min, I cant find the error. It doesnt occur for me even when deployed and all data reset, etc.

**Comment by alifarooq9** [comment]
> @alifarooq9 I tried for another like 30 min, I cant find the error. It doesnt occur for me even when deployed and all data reset, etc.

It will not appear to you because you have your lemon api key, but for me its my lemon key that doesn't have your plans. That's why I am asking you to replace the variant hard quoted ids to env vars so we both can enter our own variant ids.

**Comment by DaniEnsi** [comment]
Oh now I get it... That's my bad. Sorry I was trying to understand what you meant... I'll do it in a sec

**Comment by DaniEnsi** [comment]
Actually still didn't understand, but It should work for you now...

**Pull request merged**
